# -*- coding: utf-8 -*-
"""ift6285p1_tfidf/mlp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JcpIKcucLw5r7ur8VZQji5l-wMRtNXo1
"""

import numpy as np
import pandas as pd
import csv
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

train = pd.read_csv('msr_paraphrase_train.txt', sep = '\t', quoting=csv.QUOTE_NONE)
test = pd.read_csv('msr_paraphrase_test.txt', sep = '\t', quoting=csv.QUOTE_NONE)

n_train = train.shape[0]
n_test = test.shape[0]

x_train = []
x_test = []
y_train = []
y_test = []
for i in range(n_train):
  x_train.append(train.iloc[[i]]['#1 String'].values[0] + ' EOS ' + train.iloc[[i]]['#2 String'].values[0])
  y_train.append(train.iloc[[i]]['Quality'].values[0])
for i in range(n_test):
  x_test.append(test.iloc[[i]]['#1 String'].values[0] + ' EOS ' + test.iloc[[i]]['#2 String'].values[0])
  y_test.append(test.iloc[[i]]['Quality'].values[0])

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(x_train)
X_test = vectorizer.transform(x_test)

hidden_layer_sizes = [(100,)]
alpha = [0.1]
early_stopping = [True]

for h in hidden_layer_sizes:
  for a in alpha:
    for es in early_stopping:
      clf = MLPClassifier(alpha=a, hidden_layer_sizes=h, early_stopping=es, learning_rate = 'adaptive', random_state = 0)
      clf.fit(X_train, y_train)
      y_pred = clf.predict(X_test)
      print('train : ', clf.score(X_train, y_train))
      print('test : ', clf.score(X_test, y_test))
      print(classification_report(y_test, y_pred))

y_pred = clf.predict(X_test)

clf.score(X_train, y_train)

clf.score(X_test, y_test)

classification_report(y_test, y_pred)