# -*- coding: utf-8 -*-
"""ift6285p1_cos/tfidf/reglog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_NYT_U2b8Sm-pcFwZpSxKUa-8qSPZTw
"""

import numpy as np
import pandas as pd
import csv
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy import spatial
from sklearn.metrics.pairwise import cosine_similarity
from scipy import sparse
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

train = pd.read_csv('msr_paraphrase_train.txt', sep = '\t', quoting=csv.QUOTE_NONE)
test = pd.read_csv('mrpc-fabrice_lamarche.txt', sep = '\t', quoting=csv.QUOTE_NONE)

n_train = train.shape[0]
n_test = test.shape[0]

x_train = []
x_test = []
y_train = []
y_test = []
for i in range(n_train):
  x_train.append(train.iloc[[i]]['#1 String'].values[0])
  x_train.append(train.iloc[[i]]['#2 String'].values[0])
  y_train.append(train.iloc[[i]]['Quality'].values[0])
for i in range(n_test):
  x_test.append(test.iloc[[i]]['#1 String'].values[0])
  x_test.append(test.iloc[[i]]['#2 String'].values[0])
  y_test.append(test.iloc[[i]]['Quality'].values[0])

vectorizer = TfidfVectorizer()

X_train = vectorizer.fit_transform(x_train)
X_test = vectorizer.transform(x_test)

sim_train = cosine_similarity(X_train)
sim_test = cosine_similarity(X_test)

X_train = []
X_test = []
for i in range(n_train):
  X_train.append(sim_train[2*i,2*i+1])
for i in range(n_test):
  X_test.append(sim_test[2*i,2*i+1])

d = {'X': X_train, 'y': y_train}
df = pd.DataFrame(data=d)

sns.displot(df, x="X", hue="y", kind="kde", fill=True)

clf = LogisticRegression(random_state=0).fit(np.array(X_train).reshape(-1, 1), y_train)

y_pred = clf.predict(np.array(X_test).reshape(-1, 1))

clf.score(np.array(X_test).reshape(-1, 1), y_test)

clf.score(np.array(X_train).reshape(-1, 1), y_train)

classification_report(y_test, y_pred)